/run/verbose 1
/event/verbose 1
/tracking/verbose 1

# two beams in a generator
#
# beam #1
#
/gps/source/intensity 1.
/gps/particle neutron
#
/gps/pos/type Point
/gps/pos/centre 0.0 0.0 0.0 mm
#
/gps/ang/type iso
#
/gps/ene/type Arb
/gps/hist/type arb
#
# The Cf-252 neutron energy spectrum was taken from
# Figure 2 of A.B. Smith and  P.R. Fields, 
# Phys Rev 108 (1957) 411.
#
#                Energy (MeV)  Rel. Yield
#
/gps/hist/point  0.03791	32.71076
/gps/hist/point  0.08301	45.89684
/gps/hist/point  0.19830	59.07265
/gps/hist/point  0.34993	68.10622
/gps/hist/point  0.60544	74.34164
/gps/hist/point  0.81070	76.17980
/gps/hist/point  1.08555	73.89820
/gps/hist/point  1.55102	64.25226
/gps/hist/point  1.89664	55.40119
/gps/hist/point  2.39728	45.95365
/gps/hist/point  2.82949	37.80812
/gps/hist/point  3.50389	27.66813
/gps/hist/point  4.40363	17.72709
/gps/hist/point  5.04448	12.47039
/gps/hist/point  5.61632	8.97969
/gps/hist/point  6.24062	6.12068
/gps/hist/point  7.02125	3.73887
/gps/hist/point  8.84360	1.12916
#
# Linear interpolation between the data points is required to obtain
# the smooth energy spectrum
/gps/hist/inter Lin
#
/gps/pos/type Beam
#
# the incident surface is in the y-z plane
/gps/pos/rot1 0 1 0
/gps/pos/rot2 0 0 1
#
# the beam spot is centered at the origin and is
# of 1d gaussian shape with a 1 mm central plateau
/gps/pos/shape Circle
/gps/pos/centre 0. 0. 0. mm
/gps/pos/radius 1. mm
/gps/pos/sigma_r .2 mm
#
# the beam is travelling along the X_axis with 5 degrees dispersion
/gps/ang/rot1 0 0 1
/gps/ang/rot2 0 1 0
/gps/ang/type beam1d
/gps/ang/sigma_r 5. deg
#
# the beam energy is in gaussian profile centered at 400 MeV
/gps/ene/type Gauss
/gps/ene/mono 400 MeV
/gps/ene/sigma 50. MeV

# beam #2
# 2x the instensity of beam #1
/gps/source/add 10.
#
# this is a electron beam
/gps/particle e-
/gps/pos/type Beam
# it beam spot is of 2d gaussian profile with a 1x2 mm2 central plateau
# it is in the x-y plane centred at the orgin
/gps/pos/centre 0. 0. 0. mm
/gps/pos/halfx 0.5 mm
/gps/pos/halfy 1. mm
/gps/pos/sigma_x 0.1 mm
# the spread in y direction is stronger
/gps/pos/sigma_y 0.2 mm
#
#the beam is travelling along -Z_axis
/gps/ang/type beam2d
/gps/ang/sigma_x 2. deg
/gps/ang/sigma_y 1. deg
# gaussian energy profile
/gps/ene/type Gauss
/gps/ene/mono 600 MeV
/gps/ene/sigma 50. MeV
